### ISSUE TITLE
test party bug - Google Maps does not load correctly for Edit Profile

### ISSUE THREAD

**Issue by KartikeySharma** [gcivil-nyu-org/wed-fall24-team4#160]
Google Maps does not load correctly.

Steps to Reproduce

1. Login as a user
2. Allow/Deny Location Services (Doesn't work for both)
3. Go to Profile
4. Click Edit Profile

Screenshot:
![image](https://github.com/user-attachments/assets/469ee2b7-4a69-4d06-ac2e-281ecda422e1)

Note: This was not mentioned in the testing doc as of 11/13/2024 - 7:27 PM

**Comment by Avina20** [comment]
@KartikeySharma When you click Ok, the map works as intended. The alert is inbuilt from Google, but I agree this might be confusing for the customer. Good catch, we'll try to incorporate the exception in our doc.

**Comment by KartikeySharma** [comment]
@Avina20 I believe that clicking Ok after not being able to intuitively see the marker as a user is not an exception unless you want to get rid of the map functionality from Edit Profile and ask the user to enter coordinates. (which I would not prefer as a user)

The alert says that this page can't load Google Maps correctly. That basically renders your functionality of showing the marker the user chooses as obsolete. (which should not be happening)
Also, as for the alert inbuilt from Google, it might be an issue with the API_KEY cause I believe that the main home screen map also uses GOOGLE MAPS, and there is NO alert inbuilt from Google for the map on the home screen.

Please let me know what you feel about this.
