### ISSUE TITLE
test party bug - Start and End Location (A and B) bug out

### ISSUE THREAD

**Issue by KartikeySharma** [gcivil-nyu-org/wed-fall24-team4#163]
### Note: I assume A and B are the Start and End Markers, respectively. Please slack me if I am wrong.
_If I am wrong, then please explain what A and B intend to be and why there are multiple A's sometimes on the same end and sometimes A and B on the other side._

### Steps to Reproduce:

1. Login
2. Accept/Deny Location Services
3. Enter Start and End Location
4. In most cases, the start, end, and middle points are not marked correctly (Sometimes All As, sometimes some of them are Bs)

### Recording:
[Link](https://drive.google.com/file/d/1zI1eHzDkKQULZicBj4X3NzuIKOuHEorH/view?usp=sharing)

### Screenshots:
![image](https://github.com/user-attachments/assets/b84ef1ff-cf54-4374-beea-55cf9f6f255e)

![image](https://github.com/user-attachments/assets/844ff50e-984f-4115-a019-3ddc268fc2ff)

![image](https://github.com/user-attachments/assets/99b10a70-0ac2-4bce-a6e6-00698f1a342f)

![image](https://github.com/user-attachments/assets/d831c73e-369c-4111-a969-01b27c04fcd9)

### Note: This was not mentioned in the testing doc as of 11/13/2024 - 8:16 PM

**Comment by KartikeySharma** [comment]
Note: I used `Bayridge Avenue, Brooklyn` as the start location for the screenshots. However, the recording has `Jay St MetroTech` as the starting location

**Comment by KartikeySharma** [comment]
@jsi238 Can I know if this issue was resolved in the latest sprint? (Just to know if it has been closed due to completion)

If not, I would have appreciated a comment regarding what the team thinks about this issue. Do you mind sharing your insights on this issue?

**Comment by jsi238** [comment]
I was not the one who worked on the fix, but I will let the one who did know, and he can respond.

**Comment by KartikeySharma** [comment]
Not sure if the issue should be closed then :)

**Comment by willy0905591915** [comment]
> Not sure if the issue should be closed then :)


> @jsi238 Can I know if this issue was resolved in the latest sprint? (Just to know if it has been closed due to completion)
> 
> If not, I would have appreciated a comment regarding what the team thinks about this issue. Do you mind sharing your insights on this issue?

Yea it has been fixed.

**Comment by KartikeySharma** [comment]
Great job guys!
