### ISSUE TITLE
Testing Party Bug: Cross-Site Scripting (XSS) Vulnerability in Chatroom

### ISSUE THREAD

**Issue by shub-garg** [gcivil-nyu-org/wed-fall24-team4#165]
### **Description**
The chatroom functionality in the application is vulnerable to Cross-Site Scripting (XSS) attacks. Malicious scripts submitted via chat messages are being rendered as executable HTML elements, allowing potential execution of arbitrary JavaScript code in users' browsers. During testing, submitting a crafted `<a>` and `<img>` tag resulted in a clickable link and a broken image respectively, both later showing an alert box with a 'XSS Test Successful' message.

### **Steps to Reproduce**
1. **Log In to the Application:**
   - Use a test account to login.

2. **Navigate to the Chatroom:**
   - Enter any available chatroom within the application.

3. **Submit a Malicious Chat Message:**
   - In the message input field, enter the following payload:
     ```html
     <a href="javascript:alert('XSS Test Successful')">Click me</a>
     ```
OR

     ```html
     <img src="invalid-url" onerror="alert('XSS Test Successful')">
     ```

   - Send the message.

![ScreenRecording2024-11-14at4 23 13AM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/3dc31380-1e0c-4eaf-a5fc-35c864e5bcfd)

4. **Observe the Behavior:**
   - **Rendered Message:** The message displays as a clickable link labeled "Click me".
   - **Broken Image:** A broken image icon appears alongside the message.
   - **Alert Box:** An alert box appears saying XSS test sucessfull.

5. **Interact with the Rendered Content:**
   - Click on the "Click me" link to trigger the JavaScript `alert`.

### **Expected Behavior**
- **Sanitized Output:** The chat message should display the HTML tags as plain text without rendering them.
- **No Executable Scripts:** No JavaScript should execute, and no alert box should appear when interacting with the message.
- **No Broken Images:** No broken image icons should be present unless intentionally included.

### **Impact**
- **Security:** Allows attackers to execute arbitrary JavaScript in the context of users' browsers, leading to potential session hijacking, data theft, or unauthorized actions.
- **User Trust:** Compromises user confidence in the application's security measures.
- **Data Integrity:** Potential manipulation or defacement of the chat interface.

---

**Comment by rsc1102** [comment]
Good catch @shub-garg.
