### ISSUE TITLE
[Testing Party Bug] Unable to mark the route as Favorite Route using heart icon

### ISSUE THREAD

**Issue by TekuriSaiAkhil** [gcivil-nyu-org/wed-fall24-team4#168]
**Description:**
Unable to mark the route as Favorite Route using the heart icon after entering Starting Point: and Ending Point:
 and clicking heart icon

**Steps to Reproduce:**

- Login
- Enter brooklyn in the Starting Point field
- Enter manhattan in the Ending Point field
- Click heart icon

"Please enter both start and destination locations." Message shown up even after entering valid Starting Point and Ending Point 

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/935e4e8b-10d7-4a69-a2e2-7907af535cb0">
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/e93da4af-29a7-4ef5-a105-443f5d79cec6">

**Expected Behavior:**
Should be able to validate, display the route view and save the Favorite Route,

**Comment by Avina20** [comment]
@TekuriSaiAkhil Good catch, but for favouriting a route, you need to click on Find Route first. When the route is generated only then you can favourite it. But I agree we could disable the  button before the route is generated to avoid any confusion for customers.
