### ISSUE TITLE
[Testing Party Bug] Too large of an input for search on subway tab causes a 414 error

### ISSUE THREAD

**Issue by omerfarukbasar** [gcivil-nyu-org/wed-fall24-team4#170]
**Description**
On the subway tab, when searching for a station, if you enter too large of an input it will cause a 414 Request-URI Too Large error to appear

**Steps to Reproduce**
1. Go to subway tab
2. Enter a very large input, should be a couple thousand characters.
3. Hit Enter
4. Observe the 414 Request-URI Too Large message appear.

**Expected Behavior**
It should probably limit the overall input size in the text field to not allow that. I believe this is already done for other text fields.

**Screenshots or Code Snippets (required)**
<img width="1280" alt="Screenshot 2024-11-15 at 2 04 44 AM" src="https://github.com/user-attachments/assets/f087d66e-9491-4759-81b9-b24d7b6d8cbe">
<img width="1280" alt="Screenshot 2024-11-15 at 2 05 00 AM" src="https://github.com/user-attachments/assets/214b433f-6e6a-4596-a5b0-23667fb102ea">

**Comment by seanpanpan321** [comment]
Hi @omerfarukbasar , I tested with a 10,000-character input but couldn’t replicate the issue. Could you share the input size that triggers the error?

**Comment by omerfarukbasar** [comment]
Hi @seanpanpan321, I tested this using a much larger input. It was around 100,000 characters. I used [this website](https://lingojam.com/CreepyZalgoTextGenerator) to generate a text with a large amount of combining characters. First type in a text, set the craziness level to max. Copy the result and paste it multiple times into the username field. Please let me know if you are still unable to replicate the issue.

I think it might be combining characters in general, because I just tried it again using the same text generation and it crashed with only 5000 characters.
